# Generated by Django 5.0 on 2024-01-29 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todogroups',
            name='tasks',
        ),
        migrations.AddField(
            model_name='todogroups',
            name='tasks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todoApp.tasks'),
        ),
    ]
