# Generated by Django 5.0 on 2024-01-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_remove_todogroups_tasks_todogroups_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todogroups',
            name='tasks',
        ),
        migrations.AddField(
            model_name='todogroups',
            name='tasks',
            field=models.ManyToManyField(to='todoApp.tasks'),
        ),
    ]
