# Generated by Django 5.0 on 2024-01-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
