# Generated by Django 5.0 on 2024-01-30 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todogroups',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='todo_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todoApp.todogroups'),
        ),
        migrations.AlterField(
            model_name='todogroups',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
