# Generated by Django 5.0 on 2024-01-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_remove_todogroups_tasks_tasks_todo_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.comments'),
        ),
    ]
