# Generated by Django 5.0 on 2024-01-30 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0010_comments_alter_tasks_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='todogroups',
            options={'verbose_name': 'TodoGroup'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
