# Generated by Django 5.0 on 2024-01-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0011_alter_comments_options_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoApp.tasks'),
        ),
    ]
