# Generated by Django 5.0 on 2024-01-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0012_remove_tasks_comments_comments_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='tasks',
            new_name='task',
        ),
    ]
