# Generated by Django 5.0 on 2024-01-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0013_rename_tasks_comments_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todogroups',
            old_name='users',
            new_name='user',
        ),
    ]
